# Generated by Django 5.1 on 2024-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loja', '0006_rename_data_entrega_pedido_data_de_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='contato',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
